### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [ebogo1/mapgen#1]
Hello, under what license is this project released under ? Thank-you.

**Comment by suprafun** [comment]
Sorry to bother you, was wondering if you have seen this issue. Thank-you.

**Comment by ebogo1** [comment]
Hi, just noticed this now; apologies for the delayed response. You can use this code and the 3D models included as you'd like. Cheers!

**Comment by suprafun** [comment]
Thank you so very much. Just to be sure, could I use the source code to learn from it, under the MIT license ? Thank you.

**Comment by ebogo1** [comment]
Go for it.
